### ISSUE TITLE
Backend issue

### ISSUE THREAD

**Issue by makkahwi** [creativetimofficial/vue-now-ui-dashboard-laravel#2]
Something is wrong in the code, probably in the backend code

When I try to do login or register and I watch the network on my browser, both requests' status is frozen @ pending forever.
![image](https://user-images.githubusercontent.com/72427410/116333511-2214f100-a806-11eb-8ce0-c89264bcd0fd.png)

In the meanwhile, when I try to visit the backend server @ http://localhost:8000/ when having these requests pending, the "Laravel json:api" page don't show up. Also keeps loading forever, despite the fact that before sending any requests from frontend to backend code, I can visit the page n have it shown like second photo below 
![image](https://user-images.githubusercontent.com/72427410/116333546-36f18480-a806-11eb-982e-f0bd511220d6.png)
while having pending requests 

![image](https://user-images.githubusercontent.com/72427410/116333628-5c7e8e00-a806-11eb-8ee8-59ae11b7fc80.png)
with no pending requests

**Comment by teamupdivision** [comment]
Hi @makkahwi,

Thanks for reporting this issue and adding all the details. 

We've pushed a fix to this problem.
You can either download again the product from the downloads section in the Creative Tim website or check the latest commit we did in this Github repository.

Please let us know if everything works well afterwards or if there is any other issues.

All the best,
UPDIVISION Team

**Comment by makkahwi** [comment]
I got this problem after you made you latest commit on 27th Apr. So that package.json solved another issue but not this one.

**Comment by makkahwi** [comment]
![image](https://user-images.githubusercontent.com/72427410/117242522-53f10d80-ae2d-11eb-822a-ec0351a7e456.png)

Problem isn't solved, n also there is an error in the outlook

**Comment by teamupdivision** [comment]
Hi @makkahwi,

Thank you very much. Could you please send the .env for both the frontend and backend, please? Also, could you please let us know if this is working in postman? Thank you very much.

Best,
Updivision Team

**Comment by manoelfilho** [comment]
Hello. I am trying to use this free version of laravel, but API is frozen yet. Is there a specifi reason for it?

My .env do Vue app:

VUE_APP_BASE_URL=http://localhost:8080/
VUE_APP_API_BASE_URL=http://127.0.0.1:8000/api/v1/
VUE_APP_API_KEY=
VUE_APP_IS_DEMO=

My .env of API Laravel:

APP_NAME=ProjectTest
APP_ENV=local
APP_KEY=base64:...PqxtRrChLdG+XQ...
APP_DEBUG=true
APP_URL=

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=database
DB_USERNAME=root
DB_PASSWORD=root

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=useername
MAIL_PASSWORD=pass
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

**Comment by teamupdivision** [comment]
Hi @manoelfilho,

Thank you for using Creative Tim products and for sharing this. Can you please give us a few details on the error you are getting?  Also, if you can send to us a screenshot or video recording with the steps, it will help a lot in investigating this further.

Additionally, could you please check and let us know if the API project server was running?

Let us know. 

All the best,
Updivision Team

**Comment by manoelfilho** [comment]
@teamupdivision I tried to use the free version before get the paid version, but the API Laravel doesn't respond. It is only frozen and nothing more. I don't receive informations in Laravel logs.

**Comment by teamupdivision** [comment]
Hi @manoelfilho,

We were not able to reproduce this. If you can share a video recording with the steps followed, it will be really helpful. Please let us know.

Thanks,
Updivision Team

**Comment by teamupdivision** [comment]
Hi there @manoelfilho,

We would like to check if the issue was solved or if you can share a few more details on the steps followed. Please let us know if there is anything else we can help with and if you have any other issues.

Best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @manoelfilho, 

Just checking if the issue was solved or if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @manoelfilho,
 
Hope the issue has been solved. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
